import React from "react";
import { LegalSection } from "@/components/LegalLayout";

export function TermsContent() {
  return (
    <>
      <LegalSection number={1} title="Acceptance of Terms">
        <p>
          By accessing or using the TRAVLR Vacation Homes website at staytrvlr.com, our
          AI-powered property estimate tool, our homeowner partnership program, or any
          related services (collectively, the &quot;Services&quot;), you agree to be bound by
          these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you
          may not access or use the Services. Your continued use of the Services after any
          changes to these Terms constitutes acceptance of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection number={2} title="Description of Services">
        <p>
          TRAVLR Vacation Homes provides luxury vacation rental property management
          services, including marketing, guest services, and concierge support for property
          owners. The Services include:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Full-service vacation rental management for homeowners who partner with us;</li>
          <li>An AI-powered property revenue estimate tool that generates projected rental income figures for properties;</li>
          <li>Our Homeowner Partnership Program, under which TRAVLR manages and operates owner properties as short-term rentals; and</li>
          <li>The guest booking experience for stays at properties in our portfolio.</li>
        </ul>
        <p>These Terms apply to all visitors and users of the website and the Services.</p>
      </LegalSection>

      <LegalSection number={3} title="Eligibility">
        <p>
          You must be at least eighteen (18) years of age to use the Services. By using the
          Services, you represent and warrant that you are of legal age to form a binding
          contract and that you have the legal authority to act on behalf of any property
          about which you submit information or request an estimate. Where you submit
          information about a property you do not own, you represent that you have the
          authority to do so. These eligibility requirements align with the representations
          required of homeowners under our Partnership Agreement.
        </p>
      </LegalSection>

      <LegalSection number={4} title="Property Estimates & AI-Generated Content Disclaimer">
        <p>
          Property estimates provided through this website are projections based on available
          market data and are not guarantees of actual revenue. Figures are for informational
          purposes only and do not constitute a binding offer or contractual commitment.
          Actual results depend on market conditions, property specifics, and operational
          factors outside TRAVLR&apos;s control.
        </p>
        <p>
          The revenue estimates and other content generated by our property estimate tool
          are produced using artificial intelligence and available market data. You
          acknowledge and agree that:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>All estimates are projections based on available data and are not guarantees of actual revenue or performance;</li>
          <li>Estimates are provided for informational purposes only and do not constitute a binding offer, quote, or contractual commitment of any kind; and</li>
          <li>Actual results depend on market conditions, property specifics, guest demand, operational factors, and other variables outside TRAVLR&apos;s control.</li>
        </ul>
        <p>
          TRAVLR does not represent or warrant that any projected revenue figure will be
          achieved. Any reference to potential or &quot;predictable income&quot; reflects
          expected ranges, not guaranteed income. You should not rely on any estimate as a
          promise of specific results.
        </p>
      </LegalSection>

      <LegalSection number={5} title="SMS / Messaging Terms">
        <p>
          By providing your phone number, you consent to receive calls and text messages from
          TRAVLR at the number you provided, including messages sent using an automatic
          telephone dialing system or artificial or prerecorded voice. The following terms
          apply:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Message frequency varies.</li>
          <li>Message and data rates may apply.</li>
          <li>Reply &quot;STOP&quot; to opt out of SMS messages, or &quot;HELP&quot; for help.</li>
          <li>Consent to receive SMS is not a condition of using the Services or purchasing any product or service.</li>
          <li>Opt-in occurs through web form submission (where you provide your mobile number and check the SMS consent checkbox) or through verbal consent provided during agent calls.</li>
          <li>We do not share mobile contact information or SMS opt-in data with third parties or affiliates for marketing or promotional purposes.</li>
          <li>You may opt out at any time by replying &quot;STOP&quot; to any message.</li>
        </ul>
      </LegalSection>

      <LegalSection number={6} title="User Submissions & Accuracy">
        <p>
          When you submit information through the estimate form, info-request links, or any
          other channel — including your name, phone number, email address, and property
          address — you are responsible for the accuracy and completeness of that
          information. You authorize TRAVLR to use the information you submit to provide the
          Services, including generating estimates and contacting you. Providing false,
          inaccurate, or misleading information may result in termination of your access to
          the Services.
        </p>
      </LegalSection>

      <LegalSection number={7} title="Intellectual Property">
        <p>
          The website, the TRAVLR name and branding, our AI Property Reports, the Prospect
          Finder platform, and all related content, software, and technology are the
          property of TRAVLR Vacation Homes and are protected by applicable intellectual
          property laws. You may not copy, reproduce, distribute, or create derivative works
          from any TRAVLR-owned materials without our prior written consent.
        </p>
      </LegalSection>

      <LegalSection number={8} title="Third-Party Services & Links">
        <p>
          The Services integrate with and may link to third-party providers, including
          Stripe for payment processing, DocuSign for electronic signatures, and Twilio for
          calls and SMS messaging. Each third-party service is governed by its own terms of
          service and privacy policy, which TRAVLR does not control and is not responsible
          for. Your use of any third-party service is solely between you and that provider.
        </p>
      </LegalSection>

      <LegalSection number={9} title="Limitation of Liability">
        <p>
          To the fullest extent permitted by law, TRAVLR Vacation Homes and its affiliates
          shall not be liable for any indirect, incidental, special, consequential, or
          punitive damages arising out of or related to your use of the Services. Because
          the property estimate tool produces AI-generated, informational content that is
          not a guarantee of actual results (see Section 4), TRAVLR shall not be liable for
          any reliance on or use of such estimates, including any difference between
          projected and actual revenue. Your sole and exclusive remedy for any
          dissatisfaction with the Services is to stop using them.
        </p>
      </LegalSection>

      <LegalSection number={10} title="Indemnification">
        <p>
          You agree to indemnify and hold harmless TRAVLR Vacation Homes and its affiliates
          from and against any claims, damages, liabilities, and expenses (including
          reasonable attorneys&apos; fees) arising out of your use of the Services, your
          submission of inaccurate information, or your violation of these Terms. This
          indemnification is consistent in spirit with the mutual indemnification
          provisions of our Partnership Agreement.
        </p>
      </LegalSection>

      <LegalSection number={11} title="Dispute Resolution & Governing Law">
        <p>
          These Terms are governed by the laws of the State of California, without regard to
          its conflict-of-laws principles. The parties agree to attempt in good faith to
          resolve any dispute through negotiation before pursuing other remedies. Any
          dispute that cannot be resolved through negotiation may, subject to enforceability
          under applicable state law, be submitted to binding arbitration. The
          enforceability of arbitration clauses varies by state; the parties acknowledge
          that this dispute-resolution framework should be reviewed consistently with the
          corresponding provisions of the Partnership Agreement and may be adjusted by
          mutual agreement to comply with applicable law.
        </p>
      </LegalSection>

      <LegalSection number={12} title="Modifications to Terms">
        <p>
          TRAVLR reserves the right to update or modify these Terms at any time. When we make
          material changes, we will post the updated Terms on this page and update the
          &quot;Last updated&quot; date. Your continued use of the Services after changes
          become effective constitutes acceptance of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection number={13} title="Contact Information">
        <p>
          For questions about these Terms, please contact us:
        </p>
        <ul className="list-none space-y-1">
          <li>Email: <a href="mailto:info@staytrvlr.com" className="text-[#b89968] hover:underline">info@staytrvlr.com</a></li>
          <li>Phone: <a href="tel:+19495398862" className="text-[#b89968] hover:underline">(949) 539-8862</a></li>
        </ul>
      </LegalSection>
    </>
  );
}

export function PrivacyContent() {
  return (
    <>
      <LegalSection number={1} title="Introduction & Scope">
        <p>
          This Privacy Policy describes how TRAVLR Vacation Homes (&ldquo;TRAVLR,&rdquo;
          &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) collects, uses, and protects
          information in connection with our public website at staytrvlr.com, our AI-powered
          property estimate tool, and our homeowner partnership program (collectively, the
          &ldquo;Services&rdquo;).
        </p>
        <p>
          It applies to all visitors, prospective and current homeowners, and other users of our
          Services. If you are also a party to our Partnership Agreement, this policy works
          alongside the data provisions of that agreement.
        </p>
      </LegalSection>

      <LegalSection number={2} title="Information We Collect">
        <p>We collect information from several sources, including:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Directly submitted information:</strong> name, phone number, email address, and property address that you provide through the estimate form or information-request links.</li>
          <li><strong>Enrichment data:</strong> for leads sourced through data syncs, owner name, mailing address, and contact information obtained through licensed third-party data providers, including BatchData and People Data Labs. This is a different collection method than your direct submission and is collected only as permitted by applicable law.</li>
          <li><strong>Communications data:</strong> records of calls, text messages, and emails exchanged with TRAVLR, which may include call recordings and message content.</li>
          <li><strong>Payment and financial information:</strong> processed through Stripe Connect. TRAVLR does not directly collect or store your bank account or full payment card details.</li>
          <li><strong>Website usage data:</strong> cookies, analytics, IP address, and browser or device information.</li>
        </ul>
      </LegalSection>

      <LegalSection number={3} title="How We Use Information">
        <p>We use the information we collect to provide and improve our Services, including:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Providing property revenue estimates and management services;</li>
          <li>Outreach and communication, including calls, SMS, and email;</li>
          <li>Processing payouts through Stripe;</li>
          <li>Executing contracts through DocuSign;</li>
          <li>Improving our Services through aggregate or anonymized analysis; and</li>
          <li>Complying with legal and regulatory requirements.</li>
        </ul>
      </LegalSection>

      <LegalSection number={4} title="SMS / Text Messaging Privacy">
        <p>
          When you provide your mobile phone number and consent to receive text messages from
          TRAVLR Vacation Homes, we will only use that number to send the messages you agreed to
          receive (property management services, revenue estimates, appointment scheduling, and
          account updates).
        </p>
        <p>
          We do not sell, rent, or share your mobile number or SMS opt-in information with third
          parties or affiliates for marketing or promotional purposes.
        </p>
        <p>
          Message frequency varies. Message and data rates may apply. You can reply
          &quot;STOP&quot; at any time to opt out or &quot;HELP&quot; for help.
        </p>
        <p>
          <strong>Opt-in:</strong> SMS opt-in occurs through web form submission (where you
          provide your mobile number and check the consent box) or verbal consent provided during
          agent calls. Consent to receive SMS is not a condition of using the Services or
          purchasing any product or service. You may withdraw consent at any time by replying
          &quot;STOP&quot; to any message or by contacting us at the information below.
        </p>
      </LegalSection>

      <LegalSection number={5} title="Third-Party Service Providers">
        <p>
          We work with trusted third-party service providers to operate our business, including
          payment processing, electronic signature services, and communications infrastructure.
          These providers process information solely to help us deliver our services to you and
          are contractually restricted from using your information for their own independent
          marketing purposes. This is different from selling or sharing your information for
          third-party marketing, which we do not do.
        </p>
        <p>
          We also obtain enrichment data from licensed data providers, including BatchData and
          People Data Labs, which act as data sources for our outreach. These providers are
          subject to their own terms and applicable data-protection requirements.
        </p>
      </LegalSection>

      <LegalSection number={6} title="Data Retention">
        <p>
          We retain information for as long as necessary to provide the Services and comply with
          legal obligations. Leads marked &quot;Not a Fit&quot; and concluded homeowner
          relationships are deleted or de-identified when no longer needed, except where retention
          is required by law or to resolve disputes.
        </p>
      </LegalSection>

      <LegalSection number={7} title="Your Rights">
        <p>You have the right to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Request access to the information we hold about you;</li>
          <li>Request deletion of your information; and</li>
          <li>Opt out of communications. We maintain a &quot;Do Not Contact&quot; flag on your record &mdash; honoring your opt-out is a real, enforced mechanism within our systems, not merely a policy statement.</li>
        </ul>
        <p>
          <strong>California residents (CCPA/CPRA):</strong> California residents have the right to
          know what personal information is collected, request deletion, and opt out of the sale
          of personal information. Although TRAVLR does not sell personal information, we address
          this right as required by California law.
        </p>
        <p>
          <strong>Other states:</strong> TRAVLR operates a multi-state portfolio. Residents of
          states with their own privacy statutes may have additional rights; we will respond to
          such requests as required by applicable law.
        </p>
      </LegalSection>

      <LegalSection number={8} title="Cookies & Tracking">
        <p>
          We use cookies and analytics tools to understand website usage and improve our Services.
          You can control cookies through your browser settings; disabling cookies may affect
          some features of the website.
        </p>
      </LegalSection>

      <LegalSection number={9} title="Data Security">
        <p>
          We take reasonable measures to protect stored information, including encryption and
          access controls that limit data to authorized personnel. No system is perfectly secure,
          but we work to safeguard your information consistent with industry practice.
        </p>
      </LegalSection>

      <LegalSection number={10} title="Children's Privacy">
        <p>
          Our Services are not directed to minors, and we do not knowingly collect personal
          information from children. Given the nature of our business, property owners are adults
          by definition. If you believe we have collected information from a minor in error,
          please contact us and we will delete it.
        </p>
      </LegalSection>

      <LegalSection number={11} title="Policy Changes">
        <p>
          We may update this Privacy Policy from time to time. Material changes will be posted on
          this page with an updated &quot;Last updated&quot; date, and where appropriate we will
          provide direct notice. Your continued use of the Services after changes become effective
          constitutes acceptance of the revised policy.
        </p>
      </LegalSection>

      <LegalSection number={12} title="Contact Information">
        <p>For privacy questions or requests, please contact us:</p>
        <ul className="list-none space-y-1">
          <li>Email: <a href="mailto:info@staytrvlr.com" className="text-[#b89968] hover:underline">info@staytrvlr.com</a></li>
          <li>Phone: <a href="tel:+19495398862" className="text-[#b89968] hover:underline">(949) 539-8862</a></li>
        </ul>
      </LegalSection>
    </>
  );
}